### ISSUE TITLE
Gnome terminal profile

### ISSUE THREAD

**Issue by lafriakh** [overvale/vacme#1]
Hi, I'm using Ubuntu with Gnome Terminal emulator.

Is there any way to know the terminal color palette values.
I tried to open `vacme.terminal` file and can't find any useful data in it.

If you can export the color palette to other terminal applications would be great.

Thank you for the great work.

**Comment by dapine** [comment]
Hey @lafriakh, I just bumped at the same issue. Luckily I found [terminal.sexy](https://terminal.sexy), where you can create and convert terminal color schemes. 

So I did the following: First, imported [vacme.terminal](../blob/master/vacme.terminal) as Terminal.app and then exported as XFCE4 Terminal (it supports Gnome Terminal and many different terminal emulators).
Then just download the exported file and install on your terminal emulator.

**Comment by overvale** [comment]
Here's a screenshot of the color values in my terminal. Top row is 0-7, bottom is 8-15.

<img width="320" alt="image" src="https://user-images.githubusercontent.com/1388093/65380352-b9ab7880-dc8e-11e9-8a21-9edd71b22eb0.png">

**Comment by lafriakh** [comment]
Thank you @dapine, I installed the color scheme because of you.

Now Vacme working great with vim.

Thank you

**Comment by newptcai** [comment]
> Hey @lafriakh, I just bumped at the same issue. Luckily I found [terminal.sexy](https://terminal.sexy), where you can create and convert terminal color schemes.
> 
> So I did the following: First, imported [vacme.terminal](../blob/master/vacme.terminal) as Terminal.app and then exported as XFCE4 Terminal (it supports Gnome Terminal and many different terminal emulators).
> Then just download the exported file and install on your terminal emulator.

But how do you install the exported file?

**Comment by newptcai** [comment]
> Hey @lafriakh, I just bumped at the same issue. Luckily I found [terminal.sexy](https://terminal.sexy), where you can create and convert terminal color schemes.
> 
> So I did the following: First, imported [vacme.terminal](../blob/master/vacme.terminal) as Terminal.app and then exported as XFCE4 Terminal (it supports Gnome Terminal and many different terminal emulators).
> Then just download the exported file and install on your terminal emulator.

I exported for Gnome terminal. This gives you a bash script. Run this script in Gnome terminal and it will create a new profile with the correct colors.
